name: 'devcontainer-build-1' 
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v2
      - name: Build and release devcontainer Multi-Platform
        id: buildcontainer
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          subFolder: devcontainer1
          imageName: ghcr.io/natescherer/sre-devcontainer
          platform: linux/amd64,linux/arm64
          # runCmd: python /opt/sredevcontainer/get_tool_versions.py